vim.schedule(function()
    vim.pack.add({ "https://github.com/nvim-telescope/telescope.nvim" })
    vim.pack.add({ "https://github.com/nvim-lua/plenary.nvim" })

    vim.keymap.set("n", "<leader>ff", "<CMD>Telescope find_files<CR>", { desc = "Telescope find files" })
    vim.keymap.set("n", "<leader>fw", "<CMD>Telescope live_grep<CR>", { desc = "Telescope live grep" })
    vim.keymap.set("n", "<leader>fb", "<CMD>Telescope buffers<CR>", { desc = "Telescope find buffers" })
    vim.keymap.set("n", "<leader>fh", "<CMD>Telescope help_tags<CR>", { desc = "Telescope help page" })
    vim.keymap.set("n", "<leader>fo", "<CMD>Telescope oldfiles<CR>", { desc = "Telescope current files" })
    vim.keymap.set("n", "<leader>fm", "<CMD>Telescope marks<CR>", { desc = "Telescope find marks" })
    vim.keymap.set("n", "<leader>fz", "<CMD>Telescope current_buffer_fuzzy_find<CR>", { desc = "Telescope fuzzy find" })
    vim.keymap.set("n", "<leader>fgc", "<CMD>Telescope git_commits<CR>", { desc = "Telescope git commits" })
    vim.keymap.set("n", "<leader>fgs", "<CMD>Telescope git_status<CR>", { desc = "Telescope git status" })
end)
