##### 界面设置 #####
fs=no
border=no
geometry=50%:50%
autofit-larger=80%x80%
# force-window=immediate
osc=no
osd-bar=no
ontop=yes

##### 画质设置 #####
profile=gpu-hq
vo=gpu-next
gpu-api=auto
hwdec=auto-copy-safe
hwdec-codecs=all

video-sync=display-resample
interpolation
tscale=oversample

##### 播放设置 #####
keep-open=always
save-position-on-quit=no
input-default-bindings=no
autocreate-playlist=same
directory-mode=ignore

##### 音频/字幕 #####
audio-device=auto
audio-channels=auto-safe
audio-pitch-correction=no
audio-channels=5.1
audio-file-auto=fuzzy
audio-normalize-downmix=yes
volume=50
volume-max=100

sub-auto=fuzzy
slang=zh,en,ja
alang=ja,en,zh

sub-font='Noto Sans CJK SC'
sub-font-size=48
sub-color='#FFFFFF'
sub-border-size=3
sub-border-color='#000000'
sub-shadow-offset=1
sub-shadow-color='#000000'
watch-later-options-remove=sub-pos

secondary-sid=auto
secondary-sub-pos=95
secondary-sub-visibility=yes

##### 截图 #####
screenshot-format=jpg
screenshot-dir=~/Pictures/Screenshots/mpv/

