#!/bin/bash

parse_git_branch() {
    git branch 2> /dev/null | sed -e "/^[^*]/d" -e "s/* \(.*\)/ (\1)/"
}

PS1="╭─["
PS1+="\[\033[1;34m\]\u"
PS1+="\[\033[0m\]@"
PS1+="\[\033[1;33m\]\h"
PS1+="\[\033[0m\]] in "
PS1+="\[\033[1;36m\]  \w"
PS1+="\[\033[1;32m\]\$(parse_git_branch)"
PS1+=" \[\033[0m\]\$(printf \"%*s\" \$((\$(tput cols) - \$(echo -n \"\u\h\w\$(parse_git_branch)\" | wc -c) - 24)) \"\" | sed 's/ /·/g')\[\]"
PS1+="  \t"
PS1+="\n╰─ "
PS1+="\[\033[1;37m\]\$"
PS1+="\[\033[1;36m\] > \[\033[0m\]"

PS2="\[\033[1;36m\] → \[\033[0m\]"

export PS1
export PS2

