[backdrop]
enabled = true

[bar.default]
background_opacity = 0.69999998435378075
capsule = true
capsule_opacity = 0.91999997943639755
center = [ "clock", "theme_mode" ]
end = [ "tray", "notifications", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
margin_edge = 5
margin_ends = 10
start = [ "control-center", "workspaces", "active_window", "media" ]

[battery]
warning_threshold = 30

[control_center]
hidden_tabs = [ "system", "screen-time" ]
sidebar_section = "none"
width = 1000

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "clipboard"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "武汉"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@winit" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 854.0
    cy = 948.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 629.0
    cy = 1452.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[shell]
font_family = "LXGW WenKai Medium"
niri_overview_type_to_launch_enabled = false
polkit_agent = true

    [shell.launcher]
    categories = false

    [shell.panel]
    control_center_placement = "floating"
    session_placement = "floating"
    transparency_mode = "soft"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/kjuil/Pictures/Screenshots"
    filename_pattern = "screenshot_%Y%m%d_%H%M%S"

    [shell.session]
    grid = true

[system.monitor]
enabled = false

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/kjuil/.config/noctalia/wallpaper"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/kjuil/.config/noctalia/wallpaper/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/kjuil/.config/noctalia/wallpaper/wallpaper.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/kjuil/.config/noctalia/wallpaper/wallpaper.jpg"

[weather]
effects = false
refresh_minutes = 60

[widget.active_window]
max_length = 150
title_scroll = "on_hover"

[widget.clock]
format = "{:%a, %b %d, %H:%M}"

[widget.control-center]
custom_image = ""

[widget.media]
hide_when_no_media = true
max_length = 150
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.tray]
detached_panel = true
drawer = true
